### ISSUE TITLE
Content-Type: looks like charset is ignored

### ISSUE THREAD

**Issue by drankard** [chao/RESTClient#10]
I havent seen how this was implemented in previous releases, but after 1.3.4 the given charset in Content-Type looks like being ignored, if the service respond with an UTF-8 charset and the mashine running RESTClinet is set to some other encoding, it looks like the local encoding is used not the charset in the Content-Type, this results in wierd chars when the response document contains special chars.

**Comment by AnshD12** [comment]
@stiak Hi I just wanted to know this -> xmlHttpRequest.overrideMimeType("text/xml; charset=x-user-defined"); can be taken care from the UI side in my ionic application or this changes I need to do at the backend side
