### ISSUE TITLE
Send button is not working

### ISSUE THREAD

**Issue by amk41185** [chao/RESTClient#177]
Hi 
I am using Rest Client 2.0.3 on Firefox 32.0.2 I am using Window 7 PC. 
Since few days Send button is not working when I click there is no action taking place. It used to work before and I am not sure what went wrong.
  I tried to disable -> Enable from Add-on page . 
  Removed Rest client and reinstalled, 
  Reinstalled Fire fox and REST client. 
  None of the above worked. 
Appreciate your help to resolve this issue, thanks.

**Comment by rajeshbattu1** [comment]
Thats awesome buddy great work.  Keep it up.  Appreciated your help :+1:

**Comment by coding-tycoon** [comment]
Hi.

I'm also facing same issue in RESTClient 2.0.3 on Firefox 46.0.1

Resetting and reinstalling also didn't work. :(

It's not just the 'Send' button, other buttons like below are not working as well.

![error](https://cloud.githubusercontent.com/assets/19281919/15140041/f1cdae96-16b6-11e6-85e9-818cd9c42c10.png)

**Comment by coding-tycoon** [comment]
Issue is with the latest Firefox build 46 
https://addons.mozilla.org/en-US/firefox/addon/restclient/reviews/

Others are also facing similar issue

**Comment by benel** [comment]
Same as #220.
