### ISSUE TITLE
Show curl code

### ISSUE THREAD

**Issue by MatheMatrix** [chao/RESTClient#181]
RESTClient is a nice tool, but sometimes I need to show curl code to others, do we have any support?

**Comment by rjmvalk3** [comment]
+1

**Comment by andredasilvapinto** [comment]
+1

**Comment by andredasilvapinto** [comment]
seems to be a duplicate of https://github.com/chao/RESTClient/issues/110

**Comment by RockyMM** [comment]
+1

**Comment by chao** [comment]
Curl is supported in 3.0.5, please update to the latest version.
