### ISSUE TITLE
Fails on Firefox 46

### ISSUE THREAD

**Issue by abraxxa** [chao/RESTClient#220]
The Send button doesn't trigger a request, no error is seen in the developer console.

**Comment by JonathanJ-Wang** [comment]
I got the same problem.

**Comment by ishmael** [comment]
Same here.

**Comment by myasir** [comment]
Getting same issue, even i am not able to set Headers  :(

**Comment by Jalander** [comment]
same issue for me too, Unable to set Authentication and headers.

**Comment by brettdw** [comment]
Same issue with all buttons mentioned above.

**Comment by sante85** [comment]
Same here.

**Comment by gsiragusa** [comment]
Same problem.

**Comment by tonylaurent** [comment]
same issue

**Comment by bluespy** [comment]
I could confirm this too. Any logs we could provide?

**Comment by jondelatorre** [comment]
The same happened to me, I'm seeing this errors in javascript console:

Timestamp: 4/29/2016 10:28:18 AM
Error: TypeError: chrome://restclient is not a valid URL.
Source File: resource://gre/modules/LoginManagerParent.jsm
Line: 76

Timestamp: 4/29/2016 10:28:18 AM
Error: TypeError: restclient.helper is undefined
Source File: chrome://restclient/content/js/restclient.main.js
Line: 1960

**Comment by rodolfosouza** [comment]
the same here, I made downgrade to 45.0 ... all versions https://ftp.mozilla.org/pub/firefox/releases/45.0esr/win64/en-US/

**Comment by Pablosious** [comment]
Hey, developer, do you want to lose all your users?

**Comment by yugeshdevaraja** [comment]
same issue.

**Comment by atrioom** [comment]
Here for le Mac users: http://ftp.mozilla.org/pub/firefox/releases/45.0/mac/

**Comment by benel** [comment]
Investigating...

**Comment by EqbalS** [comment]
same!

**Comment by benel** [comment]
Incompatibility found: array comprehension syntax changed.

**Comment by acataluddi** [comment]
> Incompatibility found: array comprehension syntax changed.

Thank you Benel, much apreciated.

**Comment by scompo** [comment]
same here too

**Comment by czeni** [comment]
Same proble here on:
Linux HP-ProBook 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rikeoka** [comment]
Error is associated with https://github.com/chao/RESTClient/blob/13aea706fd0374842198359af2863e3e8d6707af/content/js/restclient.helper.js not loading into FF 46.  

This is failing at https://github.com/chao/RESTClient/blob/13aea706fd0374842198359af2863e3e8d6707af/content/js/restclient.main.js#L1959 with a Type Error.  

On trying to set basic auth header.
https://github.com/chao/RESTClient/blob/13aea706fd0374842198359af2863e3e8d6707af/content/js/restclient.main.js#L782 with a Type Error.

**Comment by sachinstellen** [comment]
Same issue here

**Comment by foxyterkel** [comment]
same on xubuntu. ff 46.0

**Comment by benel** [comment]
For your information, I found a fix, and I am now sending an e-mail to the maintainer in order to find the best way to publish it.

**Comment by gear54rus** [comment]
If you guys look at the network here: https://github.com/chao/RESTClient/network

It seems that my branch is the latest. I'll try to create and test a fix tomorrow (in 24hrs max, something should come up).

- If you receive some other info from maintainer, plz let me know.
- If you've got tips for me, plz leave them in the issue that was created on my repo: https://github.com/odin-public/RESTClient-APS/issues/37

**Comment by benel** [comment]
It seems I am considered by GitHub as a "collaborator" on this repository. Therefore I can publish sources. I applied the fix on the stable version (2.0.3) on a branch (see above).

@albertotn @gear54rus Let me know if it works on your forks too.

With Chao, we will try to find a solution on addons.mozilla.org to provide soon a seamless update for other users.

**Comment by albertotn** [comment]
Works fine on FF 46.0.1 (Windows)! thanks!

**Comment by riggerthegeek** [comment]
+1

Failing on FF 46.0.1 on a Mac running El Capitain

**Comment by gear54rus** [comment]
>  Let me know if it works on your forks too.

Yes, it seems to be working, thanks. I've pushed a new 1.7 release to my fork, those who require a fix immediately (update to AMO has not been pushed yet it seems: https://i.imgur.com/rs0ISUQ.png) can use that release, it doesn't remove any functionality (only adds domain-specific things).

**Comment by balihoo-acobb** [comment]
The branch made by @benel works for me until I add basic auth to the request.  In this case the Response Headers tab is cleared but the rest remain and no request is sent.

**Comment by JMVM** [comment]
Same issue with FF 46.0.1

Getting:

"El uso de getPreventDefault() está desaprobado. Use en su lugar defaultPrevented."

**Comment by albertotn** [comment]
@balihoo-acobb I'm using http basic authentication and works fine for me: request sent and received on server side

**Comment by benel** [comment]
@balihoo-acobb Could you check whether Firefox hasn't automatically reset the extension to the older version?

**Comment by Sumeet21** [comment]
same issue

**Comment by tuffz** [comment]
same issue...
```
SyntaxError: missing ] after element list
var s = [toHexString(hash.charCodeAt(i)) for (i in hash)].join("");
restcli...lper.js (Zeile 183, Spalte 45)
```
looks like @benel fixed this in https://github.com/chao/RESTClient/commit/cd1425479c84c7c4898ab76486a31bfb578dd1d7

**Comment by balihoo-acobb** [comment]
@benel I completely removed the old version and installed yours and it does in fact work.  Carry on, and thanks for the fix!

**Comment by goposky** [comment]
+1
None of the buttons are working with latest firefox v46.0.1

**Comment by CocoaKier** [comment]
Where is the solution？

**Comment by kirti5** [comment]
@CocoaKier Revert to previous version

**Comment by saerdnaer** [comment]
Just to summarize:

You can downgrade to Firefox 45,
* https://github.com/chao/RESTClient/issues/220#issuecomment-216058456
* https://github.com/chao/RESTClient/issues/220#issuecomment-216249317

wait till a new version of the addon is released
* https://github.com/chao/RESTClient/issues/220#issuecomment-216922755

or apply the patch manually – if you know how to modify an firefox addon.
* https://github.com/chao/RESTClient/commit/cd1425479c84c7c4898ab76486a31bfb578dd1d7

**Comment by saerdnaer** [comment]
@benel 
> With Chao, we will try to find a solution on addons.mozilla.org to provide soon a seamless update for other users.
Any updates there?

**Comment by benel** [comment]
> Any updates there?

Here is the fix as an XPI : 
https://github.com/chao/RESTClient/releases/download/v2.0.4/restclient-2.0.4.xpi 

It has been signed by Mozilla, therefore you should be able to install with ease in standard Firefox.
Because this version uses a different application ID, it won't replace the older RESTClient. So it is a probably a good idea to disable it first.

In the meantime, I'm trying to get "maintenership powers" on Mozilla addons site (for more seamless updates).

**Comment by benel** [comment]
Good news! I finally find a way to contact Chao! He will publish [my fix](https://github.com/chao/RESTClient/releases/download/v2.0.4/restclient-2.0.4.xpi) on Mozilla's site.

**Comment by chao** [comment]
Sorry for the chaos, I'm going to upload a new version right now.

**Comment by chao** [comment]
I have uploaded version 2.0.5, now it's waiting for review. You will be able to update RESTClient very soon.

**Comment by Puneethdevang** [comment]
Send button is not working in Mozilla Ver 58
