### ISSUE TITLE
RESTclient Send Button not working

### ISSUE THREAD

**Issue by puttarajubr** [chao/RESTClient#221]
Hi,

I am using "RESTClient 2.0.3.1-signed.1-signed" on Firefox 46.0.4
I am using Window 7 PC, From last couple of days "Send" button is not working 
when I click there is no action taking place. It used to work before and I am not sure what went wrong.

I tried following by googling around, Nothing seems to be working, 
Please suggest if you have any better solution.

1). I tried to disable -> Enable from Add-on page .
2). Removed Rest client and reinstalled,
3). Reinstalled Fire fox and REST client.

Appreciate your help to resolve this issue

Thanks in advance
--
Puttaraju

**Comment by cf700** [comment]
Having the same issue, tried exact same steps as Puttaraju

**Comment by benel** [comment]
Same as #220.
