### ISSUE TITLE
REST calls not going out

### ISSUE THREAD

**Issue by Lannyland** [chao/RESTClient#227]
The RESTClient plugin has been working great for me for a long time. Then it just suddenly stopped working. When I click send button on any REST call, it would not give any response back, as if it is not able to connect to anything.

I've tried other REST Client in Firefox such as REST Easy, and it works fine, so I know it is not a connection problem. I can also just use the address bar to do GET REST calls and get response back.

I've tried reinstalling Firefox, reinstalling the RESTClient. But nothing helped.

**Comment by orinciog** [comment]
Same happens here. It happened after I updated firefox to v46.0.
OS: Ubuntu 14.04
Firefox: v46.0
RestClient: 2.0.3.1-signed.1-signed

**Comment by ddorsner** [comment]
I started Charles and the request never leaves the browser/client. If i perform the same request in another tab, I can see the network activity,

Win 7 Pro, SP 1
Firefox: v46.0.1
RestClient: 2.0.3.1-signed.1-signed

**Comment by mrdj07** [comment]
Cannot insert headers and authentication either.

This javascript error logs in the console: restclient.helper is undefined

restclient.main.addHttpRequestHeader@chrome://restclient/content/js/restclient.main.js:625:7
restclient.main.oauthSign@chrome://restclient/content/js/restclient.main.js:1849:19
jQuery.event.dispatch@chrome://restclient/content/js/jquery.js:3331:14
jQuery.event.add/eventHandle@chrome://restclient/content/js/jquery.js:2941:5

**Comment by benel** [comment]
Same as #220.
