### ISSUE TITLE
RESTClient last update

### ISSUE THREAD

**Issue by asfor94** [chao/RESTClient#232]
Dears
The last update of your software has a bug that make RESTClient doesn't work, can you see what is the cause of this issue.
Thanks

**Comment by benel** [comment]
Do you speak about the version on Mozilla site or about [this one](https://github.com/chao/RESTClient/issues/220#issuecomment-218795568)?

**Comment by raviyerramsetty** [comment]
The version on Mozilla doesn't work for me either. The request doesn't happen when I click on "Send".

**Comment by benel** [comment]
What I meant is that version 2.0.3 doesn't work on Firefox 46. 
See #220 for more details and for manually installing version 2.0.4.

**Comment by asfor94** [comment]
I speak about that version on Mozilla.

**Comment by benel** [comment]
Then you have the solution there: https://github.com/chao/RESTClient/issues/220#issuecomment-218795568

**Comment by asfor94** [comment]
Thank you alot :+1:
