### ISSUE TITLE
can't add custom header

### ISSUE THREAD

**Issue by swizardlv** [chao/RESTClient#239]
click add custom header, then the browser window become gray and blank. no where to input the header info. seems the input dialog can't display.

please help fix thanks.

firefox : 45.2.0
Mac OSX 10.11

**Comment by vhochstein** [comment]
Same here.
firefox: 47.0.0
Mac OSX 10.11.6

editing an existing custom header is also just greying the whole browser window, but without showing any ui box

**Comment by muruga86** [comment]
Could not able to add multiple headers ....only one is allowed now
Content-Type 
Accept
User-Agent

**Comment by benel** [comment]
I confirm there is a bug. But a reproduction scenario is quite tricky to describe.
It seems to result from adding and removing favorite and custom headers in a given sequence. But I cannot figure a pattern yet.

## Workaround

Refresh the tab (with the `chrome:` URI).

**Comment by 4garfield** [comment]
same issue with Firefox 57 & RESTClient 3.0.4, cannot add "User-Agent" to header string, it's not working

**Comment by chao** [comment]
![agent](https://user-images.githubusercontent.com/55872/33749248-abf4ad80-dc07-11e7-9590-7f7689036430.png)

What do you mean you cannot add "User-Agent" to header string? Cannot you add the `user-agent` to `Headers` panel or your server side cannot get the header string?

**Comment by 4garfield** [comment]
like googlebot user-agent, "User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)", seems the server not return right response. but with another user-agent switcher extension, I see the right response

**Comment by chao** [comment]
You can use RESTClient to send a `GET` request to `https://httpbin.org/headers` (an online http test web site). `httpbin` will response all your `headers` as a JSON document.

Here is an example I am using your `User-Agent: Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' and another request header `Accept: application/json`:

![screen shot 2017-12-08 at 11 51 40 am](https://user-images.githubusercontent.com/55872/33750350-580c2fac-dc0e-11e7-99c1-8710ed4200cc.png)

Is the `User-Agent` matching the header you set?

**Comment by vlohana** [comment]
If I am trying to add the Host header  in the request, it is not considering it , I can add the header through custom header but the same value is not getting passed in the request, same way If I am trying in other rest client like postman it works fine..



![image](https://user-images.githubusercontent.com/35115512/34710695-6a28220c-f542-11e7-9258-f708af131a71.png)



Below is the same request using postman

**Comment by benel** [comment]
@vlohana What you are looking at are **response** headers and not request headers. 

As @chao said, you can query a special server like  `https://httpbin.org/headers` that will send you back your request headers as a response body.

**Comment by chao** [comment]
@vhochstein RESTClient uses XMLHttpRequest to send the HTTP requests, custom header like `Host` is not allowed.

**Comment by benel** [comment]
> RESTClient uses XMLHttpRequest to send the HTTP requests, custom header like Host is not allowed.

@chao Oh, I see. `Host`is one of the [headers that cannot be modified programmatically in Firefox](https://developer.mozilla.org/docs/Glossary/Forbidden_header_name). Maybe you could add a warning for all of them (like you did for `Referer`).

**Comment by chao** [comment]
@benel done. 

@vlohana  I will consider to implement a method to use native messaging forward HTTP request to native application. Then use the native application to execute HTTP requests. That will solve this problem.
