### ISSUE TITLE
handle the PATCH verb

### ISSUE THREAD

**Issue by ubourdon** [chao/RESTClient#240]
Hi,

It is possibel that Rest client handle the PATCH verb.
It is very useful to have this verb in REST API.

thx

**Comment by hacksonX** [comment]
Hi.
Just thought I should add that I think we need the patch indeed. Rest client is proving better than Postman everyday due to the setup we use at the office for testing.

Thanks.

**Comment by chao** [comment]
Included in RESTClient 3.0
