### ISSUE TITLE
Not able to see Favourite Requests

### ISSUE THREAD

**Issue by jadh39** [chao/RESTClient#248]
Hi Team,
I have Favourite List of Request, but suddenly it is disappear. Now I am not able to see it.

**Comment by lynchdp** [comment]
Just got upgraded to version 3.0.4 and I am experiencing the same issue, but only in a Private Firefox window.  The "Save Current Request" operation does not produce a confirmation message like it does in a non-Private window and it doesn't produce an error message either, but the request is not saved.

In a Private window, the "Manage Favorite Requests" sidebar does not contain the Favorites I saved in a non-private window.

My expectation is that I should have the ability to save Favorite Requests and access them from any Firefox window.

**Comment by chao** [comment]
The RESTClient 2 uses Firefox Add-on SDK api to store data on Firefox preference which is accessible from both private or non-private mode. Firefox 57 only support Web Extension, RESTClient was re-write by using Web Extensions. However, Web Extension cannot access Firefox preference or SQLite database. Your favorite requests are stored in IndexedDB. And in private mode IndexedDB doesn't work.

A notification will be added when you are using in Private Mode.
