### ISSUE TITLE
oAuth2 Authorization header option Bearer

### ISSUE THREAD

**Issue by JiriBendl** [chao/RESTClient#251]
Hello,
it would be great to heave possibility to add oAuth2 authorization header not only just as o OAuth2, but also Bearer.
I am using RESTClient with Keycloak auth and this would be very useful, otherwise I have to add custom header every time by hand and it's too comlicated.
Thank you
Jiri

**Comment by chao** [comment]
3.0.5 is released, please update to the latest version.
