### ISSUE TITLE
Basic Auth maximum length

### ISSUE THREAD

**Issue by DavidFricker** [chao/RESTClient#253]
It seems that If my user:key pair for HTTP basic auth are too long the client gives up and does not even attempt to make a request. For example, the base64 of the following pair causes the unexpected behavior.

46:Rdpu1gN5Rdpu1gN5Rdpu1gN5Rdpu1gN5Rdpu1gN5Rdpu1gN5Rdpu1gN5Rdpu1gN5

**Comment by chao** [comment]
Fixed in RESTClient 3.0
