### ISSUE TITLE
Rest Client Address Bar is too small

### ISSUE THREAD

**Issue by jayeshad** [chao/RESTClient#254]
Rest-client address bar looks too small just after the update.

**Comment by loonydevil** [comment]
is there any estimate when this fix is going to be available?

**Comment by smartdude4u** [comment]
That is extremely annoying :/

**Comment by strags11** [comment]
Problem was caused when Firefox removed support for their custom "-moz-calc" CSS function.  CSS3's "calc" does the same thing.  Fixing this is a simple find-and-replace.

If you would like a workaround and you are using Firefox, you can define a userContent.css file to override the setting locally.  Do a web search on "Firefox userContent.css" for instructions on where to put this file.  Inside the file, add the following:

```
@-moz-document domain(restclient) {
    #request-url { 
    	width: calc(100% - 380px) !important; 
    }
}
```
Restart Firefox and your address bar should be back to normal width.  Downside is that if the CSS ever does get fixed (or changed), you will not pick up the new code, and remembering that you made this custom override may be difficult.

**Comment by loonydevil** [comment]
yes, there are definitely a couple of workarounds (another which comes to mind is just edit this prop in inspector) but this one is a bug and should be fixed. moreover, there's PR addressing this problem, it just needs to be merged in.

**Comment by sabi0** [comment]
CSS can also be adjusted via [Stylish](https://addons.mozilla.org/en-US/firefox/addon/stylish/) add-on. No need to bother with userContent.css
And the styling is applied immediately, without browser restart. (the add-on installation does require a restart)

P.S. I've also added this rule:
```
    #request-body {
        height: 300px !important;
    }
```

**Comment by katerberg** [comment]
Fixed by https://github.com/chao/RESTClient/pull/265

**Comment by benel** [comment]
An update is published.

**Comment by chao** [comment]
Fixed in RESTClient 3
