### ISSUE TITLE
Avoid including Content-Length and Content-Type headers in DELETE requests without payload

### ISSUE THREAD

**Issue by fgalan** [chao/RESTClient#255]
As far as I have checked, RESTClient includes `Content-Length` and `Content-Type` in DELETE requests wihtout payload. Is there any way to avoid this?

Interestingly, another requests without payload (in particular GET) are not including `Content-Length` nor `Content-Type`

I'm using RESClient version 2.0.5 in Firefox 51.0.1.

Thanks!

**Comment by chao** [comment]
![screen shot 2018-01-08 at 3 44 04 pm](https://user-images.githubusercontent.com/55872/34662333-d1c9c86a-f48a-11e7-85e0-00b230147b6d.png)

This should work.

**Comment by chao** [comment]
3.0.5 is released, please update to the latest version.
