### ISSUE TITLE
Headers menu entries too small

### ISSUE THREAD

**Issue by gvwolf3d** [chao/RESTClient#257]
![restclient](https://cloud.githubusercontent.com/assets/26343073/25427815/02b9cb78-2a74-11e7-8030-009b27cb464e.PNG)
When opening the headers menu you cannot see the whole name of your favourite headers.
For instance you cannot distinguish between 'Content-Type application/json' and 'Content-Type application/xml'

**Comment by andi-klein** [comment]
Simple enough to fix by changing line restclient.main.js : 33
` headerMenuMaxLength: 25,`
to something bigger.

Sadly there hasn't been a new build in over a year, to get on top of this and other easy to fix issues (such as [#258 URL entry too short ](https://github.com/chao/RESTClient/issues/258)). And unless you are using a nightly or dev version of Firefox, there is no way of getting a modified xpi extension past security by having Mozilla sign the extension.
