### ISSUE TITLE
URL entry too short

### ISSUE THREAD

**Issue by jurandirjuks** [chao/RESTClient#258]
The URL box is too short, its dificult to search old entrys, 
before the update was fine.

**Comment by gopimanikandan** [comment]
Please fix this issue as soon as possible

**Comment by rolag-it** [comment]
The issue is in CSS  `width` rule of input element with id 'request-url'
![schermata del 2017-05-05 10-36-18](https://cloud.githubusercontent.com/assets/11524229/25738703/ddf2268e-317e-11e7-84e3-6864bd0f33c1.png)

**Comment by sbellone** [comment]
Yeah this is due to the removal of `-moz-calc` in Firefox 53: https://bugzilla.mozilla.org/show_bug.cgi?id=1331296
The fix is simply to replace `-moz-calc` by `calc`.

**Comment by asfor94** [comment]
@sbellone this is temporary  solution we need to solve this issue basically

**Comment by rdasilva** [comment]
Please fix and release...extension must be signed to use in normal Firefox.  I use RESTClient daily and this bug is driving me nuts!

**Comment by mwafi** [comment]
very big issue for me, pls fix it as soon as possible

**Comment by sabi0** [comment]
This is a duplicate of #254

**Comment by fabadoo** [comment]
document.getElementById("request-url").style.width='59%';
or
#request-url { width: 59% !important;}

But please, could you fix it !

**Comment by katerberg** [comment]
Fixed by https://github.com/chao/RESTClient/pull/265

**Comment by benel** [comment]
An update is published.
