### ISSUE TITLE
Add insecure mode for self signed certificates

### ISSUE THREAD

**Issue by ahmadooka** [chao/RESTClient#261]
Similar to curl -k option, allow SSL with self signed certificates

**Comment by ahmadooka** [comment]
This was also mentioned in issue #85

**Comment by chao** [comment]
There is no way bypass Firefox security mechanism to allow unsafe http connection , however, an instruction will be added in version 3.0.6 (which will be released in this month) to guide how to add a self signed site to the exception lists.
