### ISSUE TITLE
WebExtensions version

### ISSUE THREAD

**Issue by captainhook** [chao/RESTClient#263]
Hi,
Is there a WebExtensions version of this in the works? Firefox 57 is around the corner and I would like to see this addon live on. No pressure :')

**Comment by kukjevov** [comment]
Hi,

I am testing Firefox Developer edition which is already on version 57, it would be awesome if this extensions had version with WebExtensions support.

**Comment by benel** [comment]
It seems that @chao, the creator of RESTClient, have started to work on it: https://github.com/chao/RESTClient/commits/RESTClient3

**Comment by benel** [comment]
The update is published!!!
