### ISSUE TITLE
Firefox Quantum (v57) support missing!

### ISSUE THREAD

**Issue by MartinX3** [chao/RESTClient#269]
Firefox Quantum (v57) support missing!

When will the "RestClient3"-Branch be merged?

**Comment by chao** [comment]
new version is on the way

**Comment by MartinX3** [comment]
Thank you very much! :)

**Comment by dfumagalli** [comment]
Awesome! I had to keep an old duplicate Firefox to run my REST queries. But your extension is so good it's worth it!

**Comment by benel** [comment]
The update is on! Yahoo! Thank you very much, @chao !!!

**Comment by dfumagalli** [comment]
Thank you, thank you, thank youuuuuuuuuuu!

**Comment by chao** [comment]
You are welcome, sorry for the late updates. I'm trying to find a way to
balance my work and RESTClient.
