### ISSUE TITLE
New FF v57 version is missing response formatting!

### ISSUE THREAD

**Issue by rdasilva** [chao/RESTClient#270]
Thanks for the new Quantum v57 version, but....  it's lacking the response formatting view option tabs found in earlier versions.  It now only returns the raw JSON/XML response. Many REST API responses lack newline formatting.  Client needs formatted (pretty print) view.  A collapsible view would be nice as well.

**Comment by chao** [comment]
Yes, preview (re-format response body) for XML, JSON and HTML will be added
in the very near future.

**Comment by rdasilva** [comment]
Thanks chao.  I appreciate the effort and use the app daily (I did make a $ contribution).  I support the tools I use.  Unfortunately, it's pretty much unusable right now without human readable response formatting.

**Comment by sabi0** [comment]
In the meantime could you maybe enable response content wrapping?
Currently it is displayed as one very long line. (in case the response does not have line breaks)

**Comment by chao** [comment]
@sabi0 it’s done.

**Comment by chao** [comment]
3.0.4 has been uploaded. Please update your RESTClient to the latest version to get better response preview result.

**Comment by rdasilva** [comment]
Thanks Chao!
