### ISSUE TITLE
Exported requests from previous version not being imported now

### ISSUE THREAD

**Issue by sagardiwan** [chao/RESTClient#271]
I see that firefox updated RestClient extension today. Now I see that my requests exported with the previous version are not being imported. Also, all custom headers etc are lost.

Is there a way to get to the previous version?

**Comment by chao** [comment]
Firefox 57 is no long compatible with legacy extensions, if you are using Firefox 57 you will have to downgrade to version 56 (uninstall Firefox 57 and install Firefox 56). Then you can download and install RESTClient 2.0.5 from [Add-on version history page](https://addons.mozilla.org/en-US/firefox/addon/restclient/versions/?page=1#version-2.0.5). 

All your data (requests and headers) are still there, I just cannot find a way to migrate them.

**Comment by sagardiwan** [comment]
Thanks, going back to the older version helped.

**Comment by chao** [comment]
In version 3.0.4, there is a tool for data migration. You can copy RESTClient 2 preference data from about:config page and paste it to the data migration tool, it will import your requests, headers, urls.
