### ISSUE TITLE
text/plain not supported in the latest version

### ISSUE THREAD

**Issue by madflow** [chao/RESTClient#274]
+ FF 57
+ Latest Version from Github/Addon Market Place

A GET requests to a CSV resource with text/plain yields an empty response (in the response tab).

Try:

https://raw.githubusercontent.com/sunlightpolicy/opendata/master/USlocalopendataportals.csv

I was able to quickly hack/fix this with: 

```JS
      //index.js
        if(mime.indexOf('text/plain') >= 0)
        {
            mode = 'htmlmixed';
            $('.response-container a.preview[data-toggle="tab"]').show();
            try {
                iframeDoc.open();
                iframeDoc.write(body);
                iframeDoc.close();
            } catch (e) {
                console.error(e);
            }
        }
```

But I guess this should be properly done :D 

**Edit**: Also text/csv and probably the whole text/* family except text/html.

**Comment by chao** [comment]
Thanks
