### ISSUE TITLE
Firefox Socks Proxy Settings do not Appear to be Honoured

### ISSUE THREAD

**Issue by bryanray** [chao/RESTClient#278]
When SOCKS proxy is configured in Firefox (and they work on a standard tab), in RestClient I experience a timeout suggesting that the firewall is in the way and that the SOCKS setttings have not been applied.

**Comment by chao** [comment]
RESTClient works very well with SOCKS proxy. Because I live in China, I always use RESTClient via a SOCKS proxy ( a proxy sever at Japan) to visit twitter, facebook, instagram etc..
