### ISSUE TITLE
Headers: "Accept: application/xml" -> Not Response !

### ISSUE THREAD

**Issue by DelepY** [chao/RESTClient#280]
(language: fr-fr)
pas de réponse lorsqu'on utilise l'entête (Headers) "Accept: application/xml"
(le chrono tourne sans fin même pour une méthode GET, alors que le navigateur affiche une réponse immédiatement)
(RESTClient v3.0.4)

**Comment by chao** [comment]
Maybe your web sever responses with a header `Content-typee: text/plain` in your case? That's a bug of RESTClient 3.0.4 (Issue #274 ).

I will release 3.0.5 in this week to fix it.

**Comment by Kevin1466** [comment]
I tried POST many times, but all NO RESPONSE!
However the response headers show Status Code: 200 OK.

**Comment by chao** [comment]
@Kevin1466 The new version is under test right now, It will be released in two days.

**Comment by chao** [comment]
3.0.5 is released, please update to the latest version.
