### ISSUE TITLE
Unable to read Oauth redirect code form redirect url

### ISSUE THREAD

**Issue by nikhilnayar** [chao/RESTClient#281]
when i am trying to generate the token using Oauth 2.0 the redirect is not happing back to the rest client with auth code and hence token call is not getting executed. I see the error in the rest client "cannot read the code from redirect url".

**Comment by chao** [comment]
Are you using authorization code grant type? If so, there are the steps when you try to get the OAuth 2.0 access_token:

- Step 1: A new tab is opened and it will open your authorize endpoint. (You should see the authorization page, so you can login this web site then authorize the action).

The url should like this:
```
/authorize?response_type=code&client_id=s6BhdRkqt3&state=xyz&redirect_uri=https%3A%2F%2Fclient%2Eexample%2Ecom%2Fcb
```

- Step 2: After your approved this action, the authorization page should redirect to your `redirect endpoint`.

```
https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA&state=xyz
```

- Step 3: RESTClient will inject a content script to initialize a XHR request to token endpoint with the `code` value (`SplxlOBeZQQYbYS6WxSbIA`) from the query string.

- Step 4: Your OAuth 2.0 server should return access_token

```
{
       "access_token":"2YotnFZFEjr1zCsicMWpAA",
       "token_type":"example",
       "expires_in":3600,
       "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
       "example_parameter":"example_value"
}
```

If RESTClient show the error `Cannot read the code from redirect url`, it means the URL in the step 3 is incorrect, so RESTClient cannot get `code` parameter from the query string.

**Comment by nikhilnayar** [comment]
Yes i am using grant type authorization code, the redirect url is correct. I used earlier version of this rest client with similar setup untill Firefox upgrade and it was working fine, i am able to get authorization code too if i use redirect url as http://www. Google.com but it stays on same page when i use correct redirect url it fails after redirecting to rest client with error failed to read code from redirect url.i think it is domain problem it is not accepting code for universal redirects.

Let me know if you need more information. I can collect logs if you need any after commenting sensitive data.

Thanks
Nikhil

**Comment by chao** [comment]
Yes, that will be helpful. Could you please send me a copy of the logs from console of `Dev tools` ? 

BTW. remember to remove sensitive data before sending it

**Comment by nikhilnayar** [comment]
Here are the logs redirect url is - https://www.xxxxxx.com, As you can see below it gets the code but then unable to read it later to use it in token call and window closed without the token call.

POST 
https://shavar.services.mozilla.com/downloads 
[HTTP/1.0 200 Connection established 562ms]
[oauth2.js] remove old listener  oauth2.js:263
[oauth2.js] open a new tab <unavailable>  oauth2.js:272
"[oauth2.js] Created new tab: 6, redirect url: https://www.xxxxxx.com"  oauth2.js:274
[oauth2.js] storage saved! Object { grant_type: "authorization_code", client_id: "abbb9842-xxxx", client_secret: "zzzzzz", scope: "PII PHI OPENID", state: true, request_method: "post", authorization_endpoint: "https://xxxx.xxxxxx.com/healt…", token_endpoint: "https://xxxxx.xxxxxx.com/healt…", redirect_endpoint: "https://www.xxxxxx.com", result: Object }  oauth2.js:219
TabId: 6, Url: undefined  oauth2.js:602
GET 
https://xxxx.xxxxxx.com/xxx/xxx/auth/oauth2/authorize 
[HTTP/1.1 302 Processed 31ms]
Use of nsIFile in content process is deprecated.  NetUtil.jsm:307:12
Use of nsIFile in content process is deprecated.  filesystem.js:40:9
GET 
https://xxwww.xxxxxx.com/xxx/v/login 
[HTTP/1.1 200 OK 47ms]
"TabId: 6, Url: https://xxxxx.xxxxxx.com/xxxV/v/login?identityTransaction=YqQpbJDkqRH67xHn%2FXWieVLDqLbV3GdFJexPe8AvgbpjcW%2FVvWW2Sjq%2BZNARZ0eBpJNuVQpE1TY%2BmV73bgJ5wXy85HCnsT0JbLAhfJuYmd%2B6aZd5160AvjNC050FCVPVaFXENtM4Saks0M5USAvzsnOFkul0n5UQA7BXV5ppM%2FaB7%2FdGqkdGmMBnXh4SLunx4fVabdBxafcIp6je3%2Bmt0%2BAWvdYfbdYThyRQX5mfV4M8FrvElZf1LA5qFJfzF5tUzbvQQG8wOhpUSXTKYRtpZEqLXFTvsR3VZIeTmWQQ65uVJcy%2BbZvz7xBjdg%2Bbikbr6m9ezDLwkfXFWYGotgJZrQVjLa1WiqLglBmDGK5imgq1cNa8AGRPGaJ1QgC50sY%2F&appname=&branding=&skin=&language=&channel=web"  oauth2.js:602
A form was submitted in the windows-1252 encoding which cannot encode all Unicode characters, so user input may get corrupted. To avoid this problem, the page should be changed so that the form is submitted in the UTF-8 encoding either by changing the encoding of the page itself to UTF-8 or by specifying accept-charset=utf-8 on the form element.  jquery-2.1.4.min.js:3:5870
POST 
https://xxwww.xxxxxx.com/V/v/login 
[HTTP/1.1 302 Found 188ms]
TabId: 6, Url: undefined  oauth2.js:602
GET 
https://www.xxxxxx.com/ 
[HTTP/1.1 200 OK 46ms]
TabId: 6, Url: undefined  oauth2.js:602
"TabId: 6, Url: https://www.xxxxxx.com/?code=AAJTwekSd0huQqwVZj3I1ic2LjpuDBbM6uXHxRGUh7dJ7E9-iDE-bPQZC9LydBL7Ce4fgKWiRD6-vU_nnLOHOYRRaMjAGgZjAX7jdb9XgjQ2mqKdtOmG8AY4HYUbYiwJDQw"  oauth2.js:602
"[oauth2.js] handleTabUpdated Url: https://www.xxxxxx.com/?code=AAJTwekSd0huQqwVZj3I1ic2LjpuDBbM6uXHxRGUh7dJ7E9-iDE-bPQZC9LydBL7Ce4fgKWiRD6-vU_nnLOHOYRRaMjAGgZjAX7jdb9XgjQ2mqKdtOmG8AY4HYUbYiwJDQw opened!"  oauth2.js:605
TabId: 6, Url: undefined  oauth2.js:602
TabId: 6, Url: undefined  oauth2.js:602
GET 
http://www.xxxxxx.com/index.html 
[HTTP/1.1 302 Found 0ms]
GET 
https://www.xxxxxx.com/index.html 
[HTTP/1.1 200 OK 10ms]
"[oauth2.js] content script is running at https://www.xxxxxx.com/?code=AAJTwekSd0huQqwVZj3I1ic2LjpuDBbM6uXHxRGUh7dJ7E9-iDE-bPQZC9LydBL7Ce4fgKWiRD6-vU_nnLOHOYRRaMjAGgZjAX7jdb9XgjQ2mqKdtOmG8AY4HYUbYiwJDQw"  oauth2.js:611
[oauth2.js] start to get access token 6 "https://www.xxxxxx.com/?code=AAJTwekSd0huQqwVZj3I1ic2LjpuDBbM6uXHxRGUh7dJ7E9-iDE-bPQZC9LydBL7Ce4fgKWiRD6-vU_nnLOHOYRRaMjAGgZjAX7jdb9XgjQ2mqKdtOmG8AY4HYUbYiwJDQw" Object { grant_type: "authorization_code", client_id: "xxxx", client_secret: "xxxx", scope: "PII PHI OPENID", state: true, request_method: "post", authorization_endpoint: "https://xxxx.xxxxxx.com/healt…", token_endpoint: "https://xxxxxx.xxxxxx.com/healt…", redirect_endpoint: "https://www.xxxxxx.com", result: Object }  oauth2.js:476
TypeError: url.match(...) is null  oauth2.js:501:17
TabId: 6, Url: undefined  oauth2.js:602
"TabId: 6, Url: https://www.xxxxxx.com/index.html"  oauth2.js:602
"[oauth2.js] handleTabUpdated Url: https://www.xxxxxx.com/index.html opened!"  oauth2.js:605
GET 
TabId: 6, Url: undefined  oauth2.js:602
GET 
XHR 
"[oauth2.js] content script is running at https://www.xxxxxx.com/index.html"  oauth2.js:611
[oauth2.js] start to get access token 6 "https://www.xxxxxx.com/index.html" Object { grant_type: "authorization_code", client_id: "xxx", client_secret: "xxxxx", scope: "PII PHI OPENID", state: true, request_method: "post", authorization_endpoint: "https://xxx.xxxxxx.com/healt…", token_endpoint: "https://xxxx.xxxxxx.com/healt…", redirect_endpoint: "https://www.xxxxxx.com", result: Object }  oauth2.js:476
GET 
https://l.addthiscdn.com/live/t00/250lo.gif 
[0ms]
[background.js][handleRemoved] TabId: 6 Object { windowId: 3, isWindowClosing: false }  background.js:1
[message.js] target index, tab: undefined, action: http-oauth2-tab-closed Object { target: "index", action: "http-oauth2-tab-closed", type: "boardcast", tabId: 6 } Object { id: "{ad0d925d-88f8-47f1-85ea-8463569e75…", url: "moz-extension://13cba948-4ea0-48b8-…", envType: "addon_child", extensionId: "{ad0d925d-88f8-47f1-85ea-8463569e75…", contextId: "3-2" }  message.js:29
[message.js][http-oauth2-tab-closed] closed tab: 6, oauth2TabId: 6  message.js:113
GET 
https://safebrowsing.googleapis.com/v4/threatListUpdates:fetch 
[HTTP/1.0 200 Connection established 173ms]

**Comment by nikhilnayar** [comment]
I believe handleTabUpdated function (oauth2.js:605)should run only once, should not consider tab updates by domain scripts after the code is generated or else code should be read from location header of 302 redirect.

**Comment by chao** [comment]
@nikhilnayar 

I realized that there is a bug in my code, the following code will break the oauth processes if the redirected url has no `state` parameter.

```JavaScript
var state = url.match(/[&\?]state=([^&]+)/)[1] || false;
```

It should be
```JavaScript
matches = url.match(/[&\?]state=([^&]+)/);
var state = (Array.isArray(matches) && matches.length > 1) ? matches[1] : false;
```

I will fix it ASAP.

And the reason I have to run handleTabUpdated function multiple times is I cannot find out a way to catch 302 redirect in a tab. I will try to improve it in the future version.

Thanks for your help.

**Comment by nikhilnayar** [comment]
Sounds good, thanks for fixing it.

**Comment by chao** [comment]
3.0.6 is released, Could you please update to the latest version and try again?

**Comment by nikhilnayar** [comment]
Sorry i missed your email earlier. It worked, thanks for the fix.

**Comment by chao** [comment]
yeah!
