### ISSUE TITLE
大神！！！中文不识别以及乱码问题

### ISSUE THREAD

**Issue by ocyisheng** [chao/RESTClient#283]
1.链接中有中文参数不能识别
2.响应数据中中文乱码。。。
3.忘前辈解决

**Comment by chao** [comment]
例子贴上来啊。。。

**Comment by ocyisheng** [comment]
火狐版本是57.0.4 (64 位)的

**Comment by ocyisheng** [comment]
好

**Comment by ocyisheng** [comment]
Post请求https://cpu.baidu.com/1033/d77e414   参数pageNo=1&pageSize=10&needHybrid=1&channelld=1065

**Comment by chao** [comment]
![screen shot 2018-01-18 at 5 38 16 pm](https://user-images.githubusercontent.com/55872/35091001-674f7504-fc76-11e7-9ccd-b05898cf7441.png)

看起来没问题啊。另外如果是一个表单提交，按照HTTP协议要在Header里面增加下面的属性：
```
Content-Type: application/x-www-form-urlencoded
```

**Comment by ocyisheng** [comment]
知道了前辈，我第一次用这个插件。给你添麻烦了

**Comment by chao** [comment]
太客气了，欢迎再来！
