### ISSUE TITLE
Loading page version

### ISSUE THREAD

**Issue by llaville** [chao/RESTClient#284]
Hello,
Thanks for the new major version 3.0 ; very nice :) 

Just a little cosmetic issue on loading page. 
I have the latest version 3.0.5, what is shown on bottom right corner of main page, but on loading page it's still 3.0.0 that is displayed.

![rest_client](https://user-images.githubusercontent.com/364342/35115696-5d56d066-fc89-11e7-8731-f7d078862a35.png)

**Comment by chao** [comment]
Thanks, I will update it in the next release.

**Comment by chao** [comment]
Fixed in 3.0.6
