### ISSUE TITLE
FireFox57.0.4升级RESTClient3.0.5后，中文Response乱码

### ISSUE THREAD

**Issue by aricc** [chao/RESTClient#285]
中文表现为麻将块乱码。

![snipaste_2018-01-20_23-40-12](https://user-images.githubusercontent.com/1269692/35185200-4c6835fc-fe3b-11e7-9363-cde015240105.png)

**Comment by chao** [comment]
在response标签里也是乱码吗？服务端输出的编码方式是什么？方便把headers标签页和response标签页一并截图看看吗？

**Comment by aricc** [comment]
你好，感谢你的回复。
正好有多个问题，一并反馈给你。

以下是乱码数据的调用信息：



Response标签也是一样的乱码：




 
另外，我的首选项里只有这三个跟restclient相关的配置项。没有migration提示页面说的那几个。
1、把RestClient移除后，这三个首选项仍然存在。
2、移除后重新安装RestClient，仍然不能解决乱码问题。
3、我又移除RestClient，再卸载FF，然后重新安装FF，查看首选项，这三项就已经存在了，卸载重装并没有清除配置。
4、再次安装RestClient，问题依旧。

对了，还有个提示：
RESTClient会存取我所有网站的数据？提示的权限列表有点吓人。


发件人： Chao ZHOU
发送时间： 2018-01-21 12:52
收件人： chao/RESTClient
抄送： aricc; Author
主题： Re: [chao/RESTClient] FireFox57.0.4升级RESTClient3.0.5后，中文Response乱码 (#285)
在response标签里也是乱码吗？服务端输出的编码方式是什么？方便把headers标签页和response标签页一并截图看看吗？

**Comment by aricc** [comment]
邮件直接回复的，图片没显示出来，不知道你是否能看到邮件？
重新整理一下吧。

你好，感谢你的回复。
正好有多个问题，一并反馈给你。

以下是乱码数据的调用信息：
![default](https://user-images.githubusercontent.com/1269692/35191163-ceb7bfb4-feae-11e7-9d28-b7f9423aa511.png)
Response标签也是一样的乱码：
![default](https://user-images.githubusercontent.com/1269692/35191164-dd074b34-feae-11e7-9eaf-edefd7ec120f.png)
另外，我的首选项里只有这三个跟restclient相关的配置项。没有migration提示页面说的那几个。
1、把RestClient移除后，这三个首选项仍然存在。
2、移除后重新安装RestClient，仍然不能解决乱码问题。
3、我又移除RestClient，再卸载FF，然后重新安装FF，查看首选项，这三项就已经存在了，卸载重装并没有清除配置。
4、再次安装RestClient，问题依旧。
![default](https://user-images.githubusercontent.com/1269692/35191168-f105d2b8-feae-11e7-9844-4cec5357444f.png)
对了，还有个提示：
![default](https://user-images.githubusercontent.com/1269692/35191172-f6ff0702-feae-11e7-8faa-efe8f2213260.png)
RESTClient会存取我所有网站的数据？提示的权限列表有点吓人。

**Comment by chao** [comment]
今天周末没带电脑，乱码的问题明天测试下回复。

关于RESTClient 的about:config首选项参数不用管。因为firefox升级后已经不允许插件去操作首选项了。所以没办法删除之前历史数据。如果你用不到了你手工删除就好。

关于权限的问题，RESTClient因为在你使用的时候要通过ajax请求访问不同的网站。因此没办法在配置的时候指定具体获得某个网站的权限。因此只能使用<all_url>。看起来确实挺吓人。不过RESTClient是开放源代码项目，不放心可以查看相关代码，

**Comment by chao** [comment]
确实存在乱码问题。具体原因还不知道。目前看来Firefox的XHR返回的结果就是乱码。
![screen shot 2018-01-22 at 10 14 43 am](https://user-images.githubusercontent.com/55872/35202361-387d7462-ff5d-11e7-8791-62ad612fcfe8.png)

但是通过网络抓包返回的结果来看是没问题的。
![screen shot 2018-01-22 at 10 14 48 am](https://user-images.githubusercontent.com/55872/35202366-4773de70-ff5d-11e7-950f-8a46c0bb1091.png)


这个得详细排查一下，争取尽快修复。

**Comment by chao** [comment]
@aricc 

目前怀疑是xhr的自身mimeType造成的问题。在新版本发布前可以在Header中增加一个：
```
Content-Type: application/json;charset=UTF-8
```
临时解决一下。

![screen shot 2018-01-22 at 12 23 30 pm](https://user-images.githubusercontent.com/55872/35205309-16b24c56-ff6f-11e7-9439-6e1f91197343.png)

**Comment by aricc** [comment]
ok



 
发件人： Chao ZHOU
发送时间： 2018-01-22 12:24
收件人： chao/RESTClient
抄送： aricc; Mention
主题： Re: [chao/RESTClient] FireFox57.0.4升级RESTClient3.0.5后，中文Response乱码 (#285)
@aricc
目前怀疑是xhr的自身mimeType造成的问题。在新版本发布前可以在Header中增加一个：
Content-Type: application/json;charset=UTF-8

临时解决一下。

**Comment by chao** [comment]
在3.0.6版本中已修复，新年快乐！

**Comment by aricc** [comment]
新年快乐！
祝老兄平平安安，健健康康！
很高兴在除夕收到你的回复。



 
发件人： Chao ZHOU
发送时间： 2018-02-15 16:11
收件人： chao/RESTClient
抄送： Aricc Liu; Mention
主题： Re: [chao/RESTClient] FireFox57.0.4升级RESTClient3.0.5后，中文Response乱码 (#285)
在3.0.6版本中已修复，新年快乐！
