### ISSUE TITLE
RestClient 3.0.5版本，save current request不能保存tags

### ISSUE THREAD

**Issue by LodaShen** [chao/RESTClient#286]
@chao 貌似没把tags进行保存，导出的json文件中，tags是空的。

![default](https://user-images.githubusercontent.com/29424535/35436524-c1d3d598-02c9-11e8-83fe-7e448b20e36c.png)
![default](https://user-images.githubusercontent.com/29424535/35436551-d3959eec-02c9-11e8-89ee-8bc4570569d9.png)
![default](https://user-images.githubusercontent.com/29424535/35436591-f98b1dfc-02c9-11e8-9365-55ee1cdb0f77.png)

**Comment by chao** [comment]
确实，将在下一个版本修复。

**Comment by chao** [comment]
已经在3.0.6版本里修复。
