### ISSUE TITLE
it's automatically redirectled to the redirected page for 301/302 redirect

### ISSUE THREAD

**Issue by guolibincn** [chao/RESTClient#287]
I want to see the direct response, don't need it to get the redirect url response, is there any setting/configuration for that?

**Comment by benel** [comment]
Same as #108.
An answer by the main developper is given at the end of https://github.com/chao/RESTClient/issues/281#issuecomment-357645598

**Comment by guolibincn** [comment]
@benel 
Thanks for your quick response!

**Comment by chao** [comment]
Firefox does't allow web extension to block the redirection, so we cannot stop the automatically redirect. But in next version RESTClient will use `webRequest` to capture server side redirect event and show all redirections in the response header tab.

![screen shot 2018-02-09 at 5 50 39 pm](https://user-images.githubusercontent.com/55872/36022044-a115c402-0dc2-11e8-8587-b88f2ab8693c.png)

**Comment by chao** [comment]
Added redirect log in v3.0.6
