### ISSUE TITLE
Can't view custom media type response

### ISSUE THREAD

**Issue by torochi** [chao/RESTClient#291]
![cap 2018-02-07 11-40-35-636](https://user-images.githubusercontent.com/18655321/35895734-1ae82ec8-0bfc-11e8-8d6a-aa988a0b4a6a.png)

When I send a request, the response is blank.

However, when I check the console, I get a response.

![cap 2018-02-07 11-41-56-979](https://user-images.githubusercontent.com/18655321/35895854-a838b4dc-0bfc-11e8-9eaf-0a73bf9ccfd0.png)

It seems like the media type is application/ds-json.

Thank you.

**Comment by chao** [comment]
That's a bug, I will fix ASAP.

**Comment by chao** [comment]
Fixed in v3.0.6.

**Comment by torochi** [comment]
Thank you!

**Comment by chao** [comment]
Fixed in v3.0.6
