### ISSUE TITLE
Content-Type: application/vnd.api+json

### ISSUE THREAD

**Issue by fisharebest** [chao/RESTClient#297]
My API responds with the header `Content-Type: application/vnd.api+json`, as per the [jsonapi.org](http://jsonapi.org) specification.

![screen shot 2018-02-20 at 11 07 18](https://user-images.githubusercontent.com/2306088/36420848-4049438c-162e-11e8-84da-0699540feac7.png)

RESTClient tells me there is no content-type header

![screen shot 2018-02-20 at 11 07 42](https://user-images.githubusercontent.com/2306088/36420869-5d054822-162e-11e8-93ac-0c6a70a8b8ce.png)

It does not show my response.  Instead, it tells me to "set response type to blob.

I cannot find any option/setting for "response type blob".

**Comment by chao** [comment]
Thanks for the report. I only maintained the mime types from [Mozilla web site](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Complete_list_of_MIME_types). I should maintained the full mime type list from [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml).

Sorry for the troubles, I will update it as soon as possible.

**Comment by chao** [comment]
Please update to version 3.0.7 and try again.

**Comment by fisharebest** [comment]
Works great.  Thanks!

**Comment by chao** [comment]
You are welcome!
