### ISSUE TITLE
Content-Type value must be equal to [text/plain;charset="UTF-8"] current [text/plain;charset=UTF-8]

### ISSUE THREAD

**Issue by epkperk** [chao/RESTClient#298]
Content-Type value must be equal to [text/plain;charset="UTF-8"] current [text/plain;charset=UTF-8]

Somehow RESTClient removed the quotation signs.

300: jar:file:///C:/Users/epkperk/AppData/Roaming/Mozilla/Firefox/Profiles/xy121e62.default/extensions/%7Bad0d925d-88f8-47f1-85ea-8463569e756e%7D.xpi!/
200: filename content-length last-modified file-type
201: META-INF/ 0 Mon,%2031%20Dec%201979%2023:00:00%20GMT DIRECTORY
201: _locales/ 0 Fri,%2001%20Dec%202017%2021:18:04%20GMT DIRECTORY
201: blank.html 19 Fri,%2001%20Dec%202017%2021:18:04%20GMT FILE
201: icons/ 0 Fri,%2001%20Dec%202017%2021:18:04%20GMT DIRECTORY
201: images/ 0 Fri,%2001%20Dec%202017%2021:18:04%20GMT DIRECTORY
201: index.html 30628 Fri,%2001%20Dec%202017%2021:18:04%20GMT FILE
201: manifest.json 809 Fri,%2001%20Dec%202017%2021:18:04%20GMT FILE
201: options.html 1520 Fri,%2001%20Dec%202017%2021:18:04%20GMT FILE
201: scripts/ 0 Fri,%2001%20Dec%202017%2021:18:04%20GMT DIRECTORY
201: styles/ 0 Fri,%2001%20Dec%202017%2021:18:04%20GMT DIRECTORY

Firefox Quantum 57.0.4 (64-bit)

**Comment by chao** [comment]
Which content-type? The `content-type` in the request header or at the response header?

**Comment by chao** [comment]
I cannot reproduce it. RESTClient can add a `Content-Type: text/plain;charset="UTF-8"` to request header, and it can also show `Content-Type: text/plain;charset="UTF-8"` from the response.


![screen shot 2018-02-23 at 10 53 51 am](https://user-images.githubusercontent.com/55872/36575826-08e472b6-1888-11e8-84a9-8087cbae199d.png)
