### ISSUE TITLE
浏览器内打开多个restClient页面，最后一次调用返回的结果会在每个restClient页面显示

### ISSUE THREAD

**Issue by AmuseBoy** [chao/RESTClient#300]
浏览器内打开多个restClient页面，最后一次调用返回的结果会在每个restClient页面显示

**Comment by chao** [comment]
请问你用的是哪个版本的RESTClient

**Comment by chao** [comment]
@AmuseBoy 我在3.0.7版本中测试没有能够复现此问题。如果还在用老版本，请升级到最新版本，修复了不少Bug。：）

**Comment by AmuseBoy** [comment]
嗯嗯
