### ISSUE TITLE
Unrelated documentation

### ISSUE THREAD

**Issue by benel** [chao/RESTClient#301]
@wisdomtools made a contribution to the project wiki: 
https://github.com/chao/RESTClient/wiki/Automated-test-and-generate-RESTful-API-documentation-through-rest-client

However, it is related to a completely different piece of software: [his own rest-client](https://github.com/wisdomtool/rest-client) rather than [Chao's RestClient](https://github.com/chao/RESTClient).

**Comment by chao** [comment]
@benel I have removed the wiki page :)
